#!/bin/sh
{
    echo Start the server
    hypnotoad /app/blacklist_checker/script/blacklist_checker
} && {
    echo Initialize list updates
    blacklist list schedule
} && {
    echo Start the minions
    blacklist jobqueue start
}